app/urls.py
# -*-coding:utf-8-*-

from django.urls import path
from . import views

app_name = 'remember'

urlpatterns = [
    path('myFriends/', views.myFriends, name='myFriends'),
    path('selectShare/', views.selectShare, name='selectShare'),
    path('selectShare/chain/', views.shareChain, name='shareChain'),
    path('selectShare/qrcode/', views.shareQRcode, name='shareQRcode'),
    path('share/join/<str:shareLink>', views.shareSave, name='shareSave'),
    path('quasiFriends/', views.quasiFriends, name='quasi'),
    path('quasiFriends/operating/', views.quasiOperating, name='quasiOperating'),
    path('myFriends/f/<int:fid>/', views.friendInfo, name='friendInfo'),
]

common/urls.py
# -*-coding:utf-8-*-

from django.urls import path
from common import views


app_name = 'common'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.logout, name='logout'),
    path('share/<str:share_link>/', views.share, name='share'),
    path('shareSuccess/', views.shareSuccess, name='shareSuccess'),
    path('myInfo/', views.myInfo, name='myInfo'),
    path('editMyInfo/', views.EditMyInfoView.as_view(), name='editMyInfo'),
    path('editMyPWD/', views.EditMyPWD.as_view(), name='editMyPWD'),
    path('search/', views.search, name='search'),
]

remember/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from error import views as error_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('remember/', include('app.urls')),
    path('', include('common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = error_views.permission_denied
handler404 = error_views.page_not_found
handler500 = error_views.page_error

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from dateutil.relativedelta import relativedelta
import uuid
import datetime

# Create your models here.


class Friend(models.Model):
    """
    friend model
    """
    def getAge(self):
        birthday = self.birthday
        year = ''
        if birthday != '':
            now = datetime.datetime.now()
            now_date = datetime.date(now.year, now.month, now.day)
            year = relativedelta(now_date, birthday).years
        return year

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    name = models.CharField(verbose_name='姓名', max_length=50)
    sex = models.SmallIntegerField(verbose_name='性别')
    birthday = models.DateField(verbose_name='生日', null=True, blank=True)
    age = getAge
    phone = models.CharField(verbose_name='手机号', max_length=11, null=True, blank=True)
    old_address = models.CharField(verbose_name='故乡', max_length=30, null=True, blank=True)
    new_address = models.CharField(verbose_name='现居地', max_length=30, null=True, blank=True)
    origin = models.TextField(verbose_name='相识', max_length=200, null=True, blank=True)
    status = models.SmallIntegerField(verbose_name='状态', default=2)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    def __str__(self):
        return self.name


class FriendPhoto(models.Model):
    """
    friend photos model
    """

    def user_directory_path(instance, filename):
        # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
        date = datetime.datetime.now()
        typ = 'file'
        if filename.endswith('.jpg'):
            typ = 'jpg'
        elif filename.endswith('.jpeg'):
            typ = 'jpeg'
        elif filename.endswith('.png'):
            typ = 'png'
        elif filename.endswith('.gif'):
            typ = 'gif'
        else:
            typ = 'other'
        filename = str(uuid.uuid1()) + '.' + typ
        return 'friend/photo/{}/{}/{}/{}/{}'.format(date.year, date.month, date.day, typ, filename)

    friend = models.ForeignKey(Friend, on_delete=models.CASCADE)
    photo_img = models.ImageField(upload_to=user_directory_path)
    photo_description = models.CharField(max_length=200, null=True, blank=True)
    status = models.SmallIntegerField(default=1)
    create_time = models.DateTimeField(auto_now_add=True)

common/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
import uuid

# Create your models here.


class UserHeadPhoto(models.Model):

    def user_directory_path(instance, filename):
        # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
        date = datetime.datetime.now()
        typ = 'file'
        if filename.endswith('.jpg'):
            typ = 'jpg'
        elif filename.endswith('.jpeg'):
            typ = 'jpeg'
        elif filename.endswith('.png'):
            typ = 'png'
        elif filename.endswith('.gif'):
            typ = 'gif'
        else:
            typ = 'other'
        filename = str(uuid.uuid1()) + '.' + typ
        return 'user/head_portrait/{}/{}/{}/{}/{}'.format(date.year, date.month, date.day, typ, filename)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    head_portrait = models.ImageField(verbose_name='头像', upload_to=user_directory_path)
    status = models.SmallIntegerField(verbose_name='状态', default=1)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

templates/pub/footer.html
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="row">
          <div class="col-6 col-md-3">
            <ul class="list-unstyled mb-0">
              <li><a href="#">First link</a></li>
              <li><a href="#">Second link</a></li>
            </ul>
          </div>
          <div class="col-6 col-md-3">
            <ul class="list-unstyled mb-0">
              <li><a href="javascript:alert('暂无, 尽情期待.');">Third link</a></li>
              <li><a href="javascript:alert('暂无, 尽情期待.');">Fourth link</a></li>
            </ul>
          </div>
          <div class="col-6 col-md-3">
            <ul class="list-unstyled mb-0">
              <li><a href="javascript:alert('暂无, 尽情期待.');">Fifth link</a></li>
              <li><a href="javascript:alert('暂无, 尽情期待.');">Sixth link</a></li>
            </ul>
          </div>
          <div class="col-6 col-md-3">
            <ul class="list-unstyled mb-0">
              <li><a href="javascript:alert('暂无, 尽情期待.');">Other link</a></li>
              <li><a href="javascript:alert('暂无, 尽情期待.');">Last link</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-4 mt-4 mt-lg-0">
        如果您有更好的意见, 可以向网站管理员提出
      </div>
    </div>
  </div>
</div>
<footer class="footer">
  <div class="container">
    <div class="row align-items-center flex-row-reverse">
      <div class="col-auto ml-lg-auto">
        <div class="row align-items-center">
          <div class="col-auto">
            <ul class="list-inline list-inline-dots mb-0">
              <li class="list-inline-item">version: 0.0.1</li>
              <li class="list-inline-item">管理员QQ:<a href="tencent://message/?uin=1220202232">1220202232</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
        Copyright © 2018 <a href="/">Remember</a>. &nbsp;&nbsp;使用Python3.6.4, Django2.0.5, Tabler.
      </div>
    </div>
  </div>
</footer>

templates/pub/search.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>{{ search }} - 搜索 - Remember</title>
    <link rel="icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/dashboard.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/charts-c3/plugin.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/maps-google/plugin.css' %}" rel="stylesheet" />
</head>
<body class="">
    <div class="page">
      <div class="page-main">
        {% include 'pub/top.html' %}
        <div class="my-3 my-md-5">
            <div class="">
                <div class="col-11 m-auto">
                    <div class="card">
                      <table class="table card-table table-vcenter text-center">
                        <tr>
                          <th class="w-1"></th>
                          <th>姓名</th>
                          <th class="d-none d-sm-table-cell">生日</th>
                          <th class="d-none d-md-table-cell">操作</th>
                        </tr>
                          {% if friends_list %}
                          {% for friend in friends_list %}
                        <tr>
                          <td>
                              <div class="avatar d-block rounded" style="background-image: url({% if friend.friendphoto_set.all.0.photo_img %}/media/{{ friend.friendphoto_set.all.0.photo_img }}{% else %}/static/image/logo-m.png{% endif %})">
                                  {% if friend.sex == 1 %}
                                      <span class="avatar-status bg-pink"></span>
                                  {% elif friend.sex == 2 %}
                                      <span class="avatar-status bg-blue"></span>
                                  {% endif %}
                              </div>
                          </td>
                          <td>{{ friend.name }}</td>
                          <td class="d-none d-sm-table-cell">
                              {% if friend.birthday %}
                                {{ friend.birthday|date:"Y-m-d" }}
                              {% else %}
                                未填
                              {% endif %}
                          </td>
                          <td class="d-none d-md-table-cell">
                              <a class="btn btn-outline-dark" href="{% url 'remember:friendInfo' friend.id %}">详情</a>
                          </td>
                        </tr>
                          {% endfor %}
                          {% else %}
                        <tr>
                          <td colspan="4">暂无好友</td>
                        </tr>
                          {% endif %}
                      </table>
                    </div>
                    <div class="card">
                        <div class="table-responsive">
                            <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
                                <thead>
                                    <tr>
                                        <th class="w-1">选择</th>
                                        <th class="w-10"><i class="icon-people"></i></th>
                                        <th>陌生人</th>
                                        <th class="text-center">手机号</th>
                                        <th class="text-center">故乡</th>
                                        <th class="text-center">现居地</th>
                                        <th class="text-center">时间</th>
                                        <th>相识</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if quasi_friends_list %}
                                {% for friend in quasi_friends_list %}
                                    <tr>
                                      <td>
                                          <div class="w-1">
                                              <label class="custom-control custom-checkbox custom-control-inline">
                                                <input type="checkbox" class="custom-control-input"
                                                       name="checkbox" value="{{ friend.id }}">
                                                <div class="custom-control-label"></div>
                                              </label>
                                          </div>
                                      </td>
                                      <td class="text-center">
                                      {% if friend.friendphoto_set.all %}
                                          {% for img in friend.friendphoto_set.all %}
                                              <div class="avatar d-block" title="{{ img.photo_description }}"
                                                   style="background-image: url('/media/{{ img.photo_img }}'); float:left;"></div>
                                          {% endfor %}
                                      {% else %}
                                          未上传
                                      {% endif %}
                                      </td>
                                      <td>
                                          <div>{{ friend.name }}</div>
                                          <div class="small text-muted">
                                              {% if friend.sex == 1 %}
                                                      女
                                                  {% elif friend.sex == 2 %}
                                                      男
                                                  {% else %}
                                                      未知
                                                  {% endif %}
                                                  {% if friend.age %}
                                                  {{ friend.age }}岁
                                              {% endif %}
                                          </div>
                                      </td>
                                      <td class="text-center">
                                          {% if friend.phone %}
                                              {{ friend.phone }}
                                          {% else %}
                                              未填
                                          {% endif %}
                                      </td>
                                      <td class="text-center">
                                          {% if friend.old_address %}
                                              {{ friend.old_address }}
                                          {% else %}
                                              未填
                                          {% endif %}
                                      </td>
                                      <td class="text-center">
                                          {% if friend.new_address %}
                                              {{ friend.new_address }}
                                          {% else %}
                                              未填
                                          {% endif %}
                                      </td>
                                      <td class="text-center">
                                          {{ friend.create_time|date:"Y-m-d H:i:s" }}
                                      </td>
                                      <td>
                                          {% if friend.origin %}
                                              {{ friend.origin }}
                                          {% else %}
                                              未填
                                          {% endif %}
                                      </td>
                                    </tr>
                                {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="8" class="text-center">暂无数据</td>
                                    </tr>
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                        <div class="">
                            {% csrf_token %}
                            <button id="through" class="btn btn-outline-primary w-25">通过</button>
                            <button id="refused" class="btn btn-outline-danger w-25">拒绝(删除)</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
      {% include 'pub/footer.html' %}
    </div>
<script src="{% static '/assets/js/require.js' %}"></script>
<script>
      requirejs.config({
          baseUrl: '/static'
      });
      //document.getElementById('home').classList.add('active');
          requirejs(['jquery'], function($){
             $(document).on('click', '#through', function(){
                 checkfun(1);
             });
             $(document).on('click', '#refused', function(){
                 checkfun(2);
             });
          });
          var csrftoken = document.getElementsByName('csrfmiddlewaretoken')[0].value;

           function csrfSafeMethod(method) {
               // these HTTP methods do not require CSRF protection
               return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
           }
          function checkfun(i){
              var chk_value =[];
              var type = i;
              var data = {};
              $('input[name="checkbox"]:checked').each(function(){
                  chk_value.push($(this).val());
              });
              if(chk_value.length == 0){
                  alert('你还没有选择任何内容！');
                  return;
              }
              if(type !== 1 && type !== 2){
                  alert('error');
                  return;
              }
              data = {
                  'type': type,
                  'value': chk_value,
              };
              $.ajax({
                  url: "{% url 'remember:quasiOperating' %}",
                  method: 'POST',
                  beforeSend:function(jqXHR, settings){
                      $('#loader-main').addClass('active');
                      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                          jqXHR.setRequestHeader("X-CSRFToken", csrftoken);
                      }
                  },
                  data: JSON.stringify(data),
                  success: function(data, textStatus, jqXHR){
                      if(data.code == 112){
                          //alert('through success 同意成功');
                      }else if(data.code == 113){
                          //alert('refused success 拒绝成功');
                      }else if(data.code == 114){
                          alert('操作失败');
                      }else{
                          alert('出现异常, 请联系管理员');
                      }
                  },
                  timeout: 3000,
                  error: function(jqXHR, textStatus, errorThrown){
                      if(textStatus === 'timeout'){
                          alert('请求超时');
                      }else{
                          alert('出现错误, 请刷新页面');
                      }
                  },
                  complete: function(jqXHR, textStatus){
                      location.reload();
                  }
              });
          }
</script>
<script src="{% static '/assets/js/dashboard.js' %}"></script>
<script src="{% static '/assets/plugins/charts-c3/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/maps-google/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/input-mask/plugin.js' %}"></script>
<script>

</script>
  </body>
</html>

templates/pub/top.html
{% load static %}
<div class="header py-4">
  <div class="container">
    <div class="d-flex">
      <a class="header-brand" href="/">
        <img src="{% static 'image/logo-l.png' %}" class="header-brand-img" alt="Remember logo">
      </a>
      <div class="d-flex order-lg-2 ml-auto">
        <div class="dropdown d-none d-md-flex">
          <a class="nav-link icon" data-toggle="dropdown">
            <i class="fe fe-bell"></i>
            <!-- <span class="nav-unread"></span> -->
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
            {% comment %}<a href="#" class="dropdown-item d-flex">
              <span class="avatar mr-3 align-self-center" style="background-image: url(demo/faces/male/41.jpg)"></span>
              <div>
                <strong>Nathan</strong> pushed new commit: Fix page load performance issue.
                <div class="small text-muted">10 minutes ago</div>
              </div>
            </a>{% endcomment %}
              <div class="text-center">
                暂无
              </div>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item text-center text-muted-dark">全部标记已读</a>
          </div>
        </div>
        <div class="dropdown">
          <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
            <span class="avatar" style="background-image: url({% if user.userheadphoto_set.last.head_portrait %}/media/{{ user.userheadphoto_set.last.head_portrait }}{% else %}/static/image/logo-m.png{% endif %})"></span>
            <span class="ml-2 d-none d-lg-block">
              <span class="text-default">{% firstof user.get_short_name user.get_username %}</span>
            </span>
          </a>
          <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
            <a class="dropdown-item" href="{% url 'common:myInfo' %}">
              <i class="dropdown-icon fe fe-user"></i> 个人资料
            </a>
            <a class="dropdown-item" href="{% url 'common:editMyPWD' %}">
              <i class="dropdown-icon fe fe-edit"></i> 修改密码
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <i class="dropdown-icon fe fe-help-circle"></i> 帮助
            </a>
            <a class="dropdown-item" href="{% url 'common:logout' %}">
              <i class="dropdown-icon fe fe-log-out"></i> 退出
            </a>
          </div>
        </div>
      </div>
      <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
        <span class="header-toggler-icon"></span>
      </a>
    </div>
  </div>
</div>
<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-3 ml-auto">
        <form class="input-icon my-3 my-lg-0" action="{% url 'common:search' %}" method="get" onsubmit="if($('#search').val()=='')return false;">
          <input type="search" id="search" name="q" class="form-control header-search" placeholder="搜索&hellip;" tabindex="1" value="{{ search }}">
          <div class="input-icon-addon">
            <i class="fe fe-search"></i>
          </div>
        </form>
      </div>
      <div class="col-lg order-lg-first">
        <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
          <li class="nav-item">
            <a href="{% url 'common:index' %}" id="home" class="nav-link"><i class="fe fe-home"></i> 主页</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'remember:myFriends' %}" id="friend" class="nav-link"><i class="fa fa-address-book-o"></i> 我的朋友</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'remember:selectShare' %}" id="share" class="nav-link"><i class="fe fe-share-2"></i> 分享我的地址</a>
          </li>
          <li class="nav-item dropdown">
            <a href="{% url 'remember:quasi' %}" id="quasi" class="nav-link"><i class="fa fa-address-book"></i> 准朋友</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>