app/urls.py
# -*-coding:utf-8-*-

from django.urls import path
from . import views

app_name = 'remember'

urlpatterns = [
    path('myFriends/', views.myFriends, name='myFriends'),
    path('selectShare/', views.selectShare, name='selectShare'),
    path('selectShare/chain/', views.shareChain, name='shareChain'),
    path('selectShare/qrcode/', views.shareQRcode, name='shareQRcode'),
    path('share/join/<str:shareLink>', views.shareSave, name='shareSave'),
    path('quasiFriends/', views.quasiFriends, name='quasi'),
    path('quasiFriends/operating/', views.quasiOperating, name='quasiOperating'),
    path('myFriends/f/<int:fid>/', views.friendInfo, name='friendInfo'),
]

common/urls.py
# -*-coding:utf-8-*-

from django.urls import path
from common import views


app_name = 'common'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.logout, name='logout'),
    path('share/<str:share_link>/', views.share, name='share'),
    path('shareSuccess/', views.shareSuccess, name='shareSuccess'),
    path('myInfo/', views.myInfo, name='myInfo'),
    path('editMyInfo/', views.EditMyInfoView.as_view(), name='editMyInfo'),
    path('editMyPWD/', views.EditMyPWD.as_view(), name='editMyPWD'),
    path('search/', views.search, name='search'),
]

remember/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from error import views as error_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('remember/', include('app.urls')),
    path('', include('common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = error_views.permission_denied
handler404 = error_views.page_not_found
handler500 = error_views.page_error

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from dateutil.relativedelta import relativedelta
import uuid
import datetime

# Create your models here.


class Friend(models.Model):
    """
    friend model
    """
    def getAge(self):
        birthday = self.birthday
        year = ''
        if birthday != '':
            now = datetime.datetime.now()
            now_date = datetime.date(now.year, now.month, now.day)
            year = relativedelta(now_date, birthday).years
        return year

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    name = models.CharField(verbose_name='姓名', max_length=50)
    sex = models.SmallIntegerField(verbose_name='性别')
    birthday = models.DateField(verbose_name='生日', null=True, blank=True)
    age = getAge
    phone = models.CharField(verbose_name='手机号', max_length=11, null=True, blank=True)
    old_address = models.CharField(verbose_name='故乡', max_length=30, null=True, blank=True)
    new_address = models.CharField(verbose_name='现居地', max_length=30, null=True, blank=True)
    origin = models.TextField(verbose_name='相识', max_length=200, null=True, blank=True)
    status = models.SmallIntegerField(verbose_name='状态', default=2)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    def __str__(self):
        return self.name


class FriendPhoto(models.Model):
    """
    friend photos model
    """

    def user_directory_path(instance, filename):
        # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
        date = datetime.datetime.now()
        typ = 'file'
        if filename.endswith('.jpg'):
            typ = 'jpg'
        elif filename.endswith('.jpeg'):
            typ = 'jpeg'
        elif filename.endswith('.png'):
            typ = 'png'
        elif filename.endswith('.gif'):
            typ = 'gif'
        else:
            typ = 'other'
        filename = str(uuid.uuid1()) + '.' + typ
        return 'friend/photo/{}/{}/{}/{}/{}'.format(date.year, date.month, date.day, typ, filename)

    friend = models.ForeignKey(Friend, on_delete=models.CASCADE)
    photo_img = models.ImageField(upload_to=user_directory_path)
    photo_description = models.CharField(max_length=200, null=True, blank=True)
    status = models.SmallIntegerField(default=1)
    create_time = models.DateTimeField(auto_now_add=True)

templates/remember/chain.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>链接 - 分享 - Remember</title>
    <link rel="icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/dashboard.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/charts-c3/plugin.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/maps-google/plugin.css' %}" rel="stylesheet" />
</head>
<body class="">
    <div class="page">
      <div class="page-main">
        {% include 'pub/top.html' %}
        <div class="my-3 my-md-5 text-center">
          <p class="h2">http://{{ request.get_host }}/share/{{ msg }}</p>

          <div id="copy" class="btn btn-primary" data-clipboard-text="http://{{ request.get_host }}/share/{{ msg }}">
            复制到粘贴板
          </div>
          <div class="container text-red text-center">
            <em>链接仅限当天有效</em>
          </div>
        </div>
      </div>
      {% include 'pub/footer.html' %}
    </div>
<script src="{% static '/assets/js/require.js' %}"></script>
    <script>
      requirejs.config({
          baseUrl: '/static'
      });
      document.getElementById('share').classList.add('active');
      require(['jquery', 'clipboard'], function($, ClipboardJS){
       // new ClipboardJS('#copy');
        var clipboard = new ClipboardJS('#copy');
        clipboard.on('success', function(e) {
            alert('已将链接复制到你的粘贴板啦.\n快分享给你的朋友吧.\n仅限当天有效哦.');
            console.info('copy success \nText:', e.text);
            e.clearSelection();
        });
        clipboard.on('error', function(e) {
            alert('复制失败, 请手动复制.sorry')
            console.error('copy:', 'error');
            console.error('Action:', e.action);
            console.error('Trigger:', e.trigger);
        });
      });
</script>

<script src="{% static '/assets/js/dashboard.js' %}"></script>
<script src="{% static '/assets/plugins/charts-c3/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/maps-google/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/input-mask/plugin.js' %}"></script>
  </body>
</html>

templates/remember/friends-list.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>我的朋友 - Remember</title>
    <link rel="icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/dashboard.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/charts-c3/plugin.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/maps-google/plugin.css' %}" rel="stylesheet" />
</head>
<body class="">
    <div class="page">
      <div class="page-main">
        {% include 'pub/top.html' %}
        <div class="my-3 my-md-5">
          <div class="container">
            <div class="page-header">
              <h1 class="page-title">
                我的朋友
              </h1>
              <div class="page-subtitle">共 {{ friends_count }} 个</div>
            </div>
            <div class="row row-cards">
              <div class="col-lg-4">
                <form class="card">
                  <div class="card-body">
                    <div class="form-group">
                      <div class="form-label">姓名</div>
                      <input id="search-name" name="name" type="text" class="form-control" value="{% if name %}{{ name }}{% endif %}"/>
                    </div>
                    <div class="form-group">
                      <div class="form-label">性别</div>
                      <div class="selectgroup w-100">
                        <label class="selectgroup-item">
                          <input type="radio" name="sex" value="3" class="selectgroup-input" {% if sex == '3' or sex is None or sex == '' %} checked{% endif %}>
                          <span class="selectgroup-button">全部</span>
                        </label>
                        <label class="selectgroup-item">
                          <input type="radio" name="sex" value="1" class="selectgroup-input" {% if sex == '1' %} checked{% endif %}>
                          <span class="selectgroup-button">女</span>
                        </label>
                        <label class="selectgroup-item">
                          <input type="radio" name="sex" value="2" class="selectgroup-input" {% if sex == '2' %} checked{% endif %}>
                          <span class="selectgroup-button">男</span>
                        </label>
                      </div>
                    </div>
                  </div>
                  <div class="card-footer text-right">
                    <div id="search" class="btn btn-outline-info">搜索</div>
                  </div>
                </form>
              </div>
              <div class="col-lg-8">
                <div class="card">
                  <table class="table card-table table-vcenter text-center">
                    <tr>
                      <th class="w-1"></th>
                      <th>姓名</th>
                      <th class="d-none d-sm-table-cell">生日</th>
                      <th class="d-none d-md-table-cell">操作</th>
                    </tr>
                      {% if friends_list %}
                      {% for friend in friends_list %}
                    <tr>
                      <td>
                          <div class="avatar d-block rounded" style="background-image: url({% if friend.friendphoto_set.all.0.photo_img %}/media/{{ friend.friendphoto_set.all.0.photo_img }}{% else %}/static/image/logo-m.png{% endif %})">
                              {% if friend.sex == 1 %}
                                  <span class="avatar-status bg-pink"></span>
                              {% elif friend.sex == 2 %}
                                  <span class="avatar-status bg-blue"></span>
                              {% endif %}
                          </div>
                      </td>
                      <td>{{ friend.name }}</td>
                      <td class="d-none d-sm-table-cell">
                          {% if friend.birthday %}
                            {{ friend.birthday|date:"Y-m-d" }}
                          {% else %}
                            未填
                          {% endif %}
                      </td>
                      <td class="d-none d-md-table-cell">
                          <a class="btn btn-outline-dark" href="{% url 'remember:friendInfo' friend.id %}">详情</a>
                      </td>
                    </tr>
                      {% endfor %}
                      {% else %}
                    <tr>
                      <td colspan="4">暂无好友</td>
                    </tr>
                      {% endif %}
                  </table>
                </div>
                <ul class="pagination ">
                  <li class="page-item page-prev {% if friends_list.number == 1 %} disabled {% endif %}">
                      <a class="page-link" href="javascript:page(1);">
                          首页
                      </a>
                  </li>
                  {% if friends_list.has_previous %}
                  <li class="page-item page-prev">
                      <a class="page-link" href="javascript:page({{ friends_list.previous_page_number }});">
                          上一页
                      </a>
                  </li>
                  {% else %}
                  <li class="page-item page-prev disabled">
                      <a class="page-link" href="javascript:void(0);">
                          上一页
                      </a>
                  </li>
                  {% endif %}
                  <li class="page-item">
                      <a class="page-link">
                          第 {{ friends_list.number }} 页
                      </a>
                  </li>
                  <li class="page-item">
                      <a class="page-link">
                          共 {{ friends_list.paginator.num_pages }} 页
                      </a>
                  </li>
                {% if friends_list.has_next %}
                  <li class="page-item page-next">
                      <a class="page-link" href="javascript:page({{ friends_list.next_page_number }});">
                          下一页
                      </a>
                  </li>
                {% else %}
                  <li class="page-item page-next disabled">
                      <a class="page-link" href="javascript:void(0);">
                          下一页
                      </a>
                  </li>
                {% endif %}
                  <li class="page-item page-next {% if friends_list.number == friends_list.paginator.num_pages %} disabled {% endif %}">
                      <a class="page-link" href="javascript:page({{ friends_list.paginator.num_pages }});">
                          尾页
                      </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% include 'pub/footer.html' %}
    </div>
<script src="{% static '/assets/js/require.min.js' %}"></script>
    <script>
      requirejs.config({
          baseUrl: '/static'
      });
      document.getElementById('friend').classList.add('active');
      requirejs(['jquery'], function($){
          $(document).on('click', '#search', function(){
              var name = $('#search-name').val();
              var sex = $('input[name="sex"]:checked').val();
              window.location.href = '{% url "remember:myFriends" %}?name=' + name + '&sex=' + sex;
          });
      });
      var name = {% if name %}'{{ name }}'{% else %}''{% endif %};
      var sex = {% if sex %}'{{ sex }}'{% else %}''{% endif %}
      function page(p){
          window.location.href = '{% url "remember:myFriends" %}?name=' + name + '&sex=' + sex + '&page=' + p;
      }
</script>
<script src="{% static '/assets/js/dashboard.js' %}"></script>
<script src="{% static '/assets/plugins/charts-c3/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/maps-google/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/input-mask/plugin.js' %}"></script>
  </body>
</html>

templates/remember/qrcode.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>二维码 - 分享 - Remember</title>
    <link rel="icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/dashboard.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/charts-c3/plugin.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/maps-google/plugin.css' %}" rel="stylesheet" />
</head>
<body class="">
    <div class="page">
      <div class="page-main">
        {% include 'pub/top.html' %}
        <div class="my-3 my-md-5 text-center">
          <img src="/{{ msg }}">
          <div class="container text-red text-center">
            <em>二维码仅限当天有效</em>
          </div>
        </div>
      </div>
      {% include 'pub/footer.html' %}
    </div>
<script src="{% static '/assets/js/require.js' %}"></script>
    <script>
      requirejs.config({
          baseUrl: '/static'
      });
      document.getElementById('share').classList.add('active');
      require(['jquery', 'clipboard'], function($, ClipboardJS){
       // new ClipboardJS('#copy');
        var clipboard = new ClipboardJS('#copy');
        clipboard.on('success', function(e) {
            alert('已将链接复制到你的粘贴板啦.\n快分享给你的朋友吧.\n仅限当天有效哦.');
            console.info('copy success \nText:', e.text);
            e.clearSelection();
        });
        clipboard.on('error', function(e) {
            alert('复制失败, 请手动复制.sorry')
            console.error('copy:', 'error');
            console.error('Action:', e.action);
            console.error('Trigger:', e.trigger);
        });
      });
</script>

<script src="{% static '/assets/js/dashboard.js' %}"></script>
<script src="{% static '/assets/plugins/charts-c3/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/maps-google/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/input-mask/plugin.js' %}"></script>
  </body>
</html>

templates/remember/quasi-friends.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>准朋友 - Remember</title>
    <link rel="icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/dashboard.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/charts-c3/plugin.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/maps-google/plugin.css' %}" rel="stylesheet" />
</head>
<body class="">
    <div class="page">
      <div class="page-main">
        {% include 'pub/top.html' %}
        <div class="my-3 my-md-5">
            <div class="row-cards row-deck">
              <div class="col-11 m-auto">
                <div class="card">
                  <div class="table-responsive">
                    <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
                        <thead>
                            <tr>
                                <th class="w-1">选择</th>
                                <th class="w-10"><i class="icon-people"></i></th>
                                <th>陌生人</th>
                                <th class="text-center">手机号</th>
                                <th class="text-center">故乡</th>
                                <th class="text-center">现居地</th>
                                <th class="text-center">时间</th>
                                <th>相识</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% if friends_list %}
                        {% for friend in friends_list %}
                            <tr>
                              <td>
                                  <div class="w-1">
                                      <label class="custom-control custom-checkbox custom-control-inline">
                                        <input type="checkbox" class="custom-control-input"
                                               name="checkbox" value="{{ friend.id }}">
                                        <div class="custom-control-label"></div>
                                      </label>
                                  </div>
                              </td>
                              <td class="text-center">
                              {% if friend.friendphoto_set.all %}
                                  {% for img in friend.friendphoto_set.all %}
                                      <div class="avatar d-block" title="{{ img.photo_description }}"
                                           style="background-image: url('/media/{{ img.photo_img }}'); float:left;"></div>
                                  {% endfor %}
                              {% else %}
                                  未上传
                              {% endif %}
                              </td>
                              <td>
                                  <div>{{ friend.name }}</div>
                                  <div class="small text-muted">
                                      {% if friend.sex == 1 %}
                                          女
                                      {% elif friend.sex == 2 %}
                                          男
                                      {% else %}
                                          未知
                                      {% endif %}
                                      {% if friend.age %}
                                          {{ friend.age }}岁
                                      {% endif %}
                                  </div>
                              </td>
                              <td class="text-center">
                                  {% if friend.phone %}
                                      {{ friend.phone }}
                                  {% else %}
                                      未填
                                  {% endif %}
                              </td>
                              <td class="text-center">
                                  {% if friend.old_address %}
                                      {{ friend.old_address }}
                                  {% else %}
                                      未填
                                  {% endif %}
                              </td>
                              <td class="text-center">
                                  {% if friend.new_address %}
                                      {{ friend.new_address }}
                                  {% else %}
                                      未填
                                  {% endif %}
                              </td>
                              <td class="text-center">
                                  {{ friend.create_time|date:"Y-m-d H:i:s" }}
                              </td>
                              <td>
                                  {% if friend.origin %}
                                      {{ friend.origin }}
                                  {% else %}
                                      未填
                                  {% endif %}
                              </td>
                            </tr>
                        {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="8" class="text-center">暂无数据</td>
                            </tr>
                        {% endif %}
                        </tbody>
                    </table>
                  </div>
                </div>
                <div class="">
                    {% csrf_token %}
                    <button id="through" class="btn btn-outline-primary w-25">通过</button>
                    <button id="refused" class="btn btn-outline-danger w-25">拒绝(删除)</button>
                </div>
              </div>
            </div>
        </div>
      </div>
      {% include 'pub/footer.html' %}
    </div>
<script src="{% static '/assets/js/require.min.js' %}"></script>
    <script>
      requirejs.config({
          baseUrl: '/static'
      });
      document.getElementById('quasi').classList.add('active');
      requirejs(['jquery'], function($){
         $(document).on('click', '#through', function(){
             checkfun(1);
         });
         $(document).on('click', '#refused', function(){
             checkfun(2);
         });
      });
      var csrftoken = document.getElementsByName('csrfmiddlewaretoken')[0].value;

       function csrfSafeMethod(method) {
           // these HTTP methods do not require CSRF protection
           return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
       }
      function checkfun(i){
          var chk_value =[];
          var type = i;
          var data = {};
          $('input[name="checkbox"]:checked').each(function(){
              chk_value.push($(this).val());
          });
          if(chk_value.length == 0){
              alert('你还没有选择任何内容！');
              return;
          }
          if(type !== 1 && type !== 2){
              alert('error');
              return;
          }
          data = {
              'type': type,
              'value': chk_value,
          };
          $.ajax({
              url: "{% url 'remember:quasiOperating' %}",
              method: 'POST',
              beforeSend:function(jqXHR, settings){
                  $('#loader-main').addClass('active');
                  if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                      jqXHR.setRequestHeader("X-CSRFToken", csrftoken);
                  }
              },
              data: JSON.stringify(data),
              success: function(data, textStatus, jqXHR){
                  if(data.code == 112){
                      //alert('through success 同意成功');
                  }else if(data.code == 113){
                      //alert('refused success 拒绝成功');
                  }else if(data.code == 114){
                      alert('操作失败');
                  }else{
                      alert('出现异常, 请联系管理员');
                  }
              },
              timeout: 3000,
              error: function(jqXHR, textStatus, errorThrown){
                  if(textStatus === 'timeout'){
                      alert('请求超时');
                  }else{
                      alert('出现错误, 请刷新页面');
                  }
              },
              complete: function(jqXHR, textStatus){
                  location.reload();
              }
          });
      }
</script>
<script src="{% static '/assets/js/dashboard.js' %}"></script>
<script src="{% static '/assets/plugins/charts-c3/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/maps-google/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/input-mask/plugin.js' %}"></script>
  </body>
</html>

templates/remember/share-success.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>成功 - Remember</title>
    <link rel="icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/dashboard.css' %}" rel="stylesheet" />
</head>
 <body class="">
    <div class="page">
      <div class="page-content">
        <div class="container text-center">
          <div class="display-1 text-muted mb-5"><i class="si si-exclamation"></i> 成功</div>
          <p class="h4 text-muted font-weight-normal mb-7">信息已加入好友的Remember中</p>
          <h1 class="h2 mb-3">想要自己的Remember吗?</h1>
          <a class="btn btn-primary" href="{% url 'common:register' %}">
            <i class="fe fe-arrow-right mr-2"></i>Yes
          </a>
        </div>
      </div>
    </div>
    <script src="{% static '/assets/js/require.min.js' %}"></script>
    <script>
      requirejs.config({
          baseUrl: '/static'
      });
    </script>
    <script src="{% static '/assets/js/dashboard.js' %}"></script>
  </body>
</html>

templates/remember/share.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>分享 - Remember</title>
    <link rel="icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/dashboard.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/charts-c3/plugin.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/maps-google/plugin.css' %}" rel="stylesheet" />
</head>
<body class="">
    <div class="page">
      <div class="page-main">
        {% include 'pub/top.html' %}
        <div class="my-3 my-md-5">
            <div class="container">
                <div class="page-header">
                  <h1 class="page-title">
                    请选择分享类型
                  </h1>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-lg-6">
                        <div class="card">
                          <div class="card-status bg-green"></div>
                          <a href="{% url 'remember:shareQRcode' %}">
                          <div class="card-body text-center">
                            <i class="fa fa-qrcode" style="font-size:200px;"></i>
                            <div class="display-3 my-4">二维码分享</div>
                          </div>
                          </a>
                        </div>
                    </div>
                    <div class="col-sm-12 col-lg-6">
                        <div class="card">
                          <div class="card-status bg-green"></div>
                          <a href="{% url 'remember:shareChain' %}">
                          <div class="card-body text-center">
                            <i class="fa fa-chain" style="font-size:200px;"></i>
                            <div class="display-3 my-4">链接分享</div>
                          </div>
                          </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container text-red text-center">
                <em>链接仅限当天有效</em>
            </div>
        </div>
      </div>
      {% include 'pub/footer.html' %}
    </div>
<script src="{% static '/assets/js/require.min.js' %}"></script>
    <script>
      requirejs.config({
          baseUrl: '/static'
      });
      document.getElementById('share').classList.add('active');
</script>
<script src="{% static '/assets/js/dashboard.js' %}"></script>
<script src="{% static '/assets/plugins/charts-c3/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/maps-google/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/input-mask/plugin.js' %}"></script>
  </body>
</html>