app/urls.py
# -*-coding:utf-8-*-

from django.urls import path
from . import views

app_name = 'remember'

urlpatterns = [
    path('myFriends/', views.myFriends, name='myFriends'),
    path('selectShare/', views.selectShare, name='selectShare'),
    path('selectShare/chain/', views.shareChain, name='shareChain'),
    path('selectShare/qrcode/', views.shareQRcode, name='shareQRcode'),
    path('share/join/<str:shareLink>', views.shareSave, name='shareSave'),
    path('quasiFriends/', views.quasiFriends, name='quasi'),
    path('quasiFriends/operating/', views.quasiOperating, name='quasiOperating'),
    path('myFriends/f/<int:fid>/', views.friendInfo, name='friendInfo'),
]

common/urls.py
# -*-coding:utf-8-*-

from django.urls import path
from common import views


app_name = 'common'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.logout, name='logout'),
    path('share/<str:share_link>/', views.share, name='share'),
    path('shareSuccess/', views.shareSuccess, name='shareSuccess'),
    path('myInfo/', views.myInfo, name='myInfo'),
    path('editMyInfo/', views.EditMyInfoView.as_view(), name='editMyInfo'),
    path('editMyPWD/', views.EditMyPWD.as_view(), name='editMyPWD'),
    path('search/', views.search, name='search'),
]

remember/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from error import views as error_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('remember/', include('app.urls')),
    path('', include('common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = error_views.permission_denied
handler404 = error_views.page_not_found
handler500 = error_views.page_error

common/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
import uuid

# Create your models here.


class UserHeadPhoto(models.Model):

    def user_directory_path(instance, filename):
        # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
        date = datetime.datetime.now()
        typ = 'file'
        if filename.endswith('.jpg'):
            typ = 'jpg'
        elif filename.endswith('.jpeg'):
            typ = 'jpeg'
        elif filename.endswith('.png'):
            typ = 'png'
        elif filename.endswith('.gif'):
            typ = 'gif'
        else:
            typ = 'other'
        filename = str(uuid.uuid1()) + '.' + typ
        return 'user/head_portrait/{}/{}/{}/{}/{}'.format(date.year, date.month, date.day, typ, filename)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    head_portrait = models.ImageField(verbose_name='头像', upload_to=user_directory_path)
    status = models.SmallIntegerField(verbose_name='状态', default=1)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

templates/user/edit-my-info.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>编辑资料 - Remember</title>
    <link rel="icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/dashboard.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/charts-c3/plugin.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/maps-google/plugin.css' %}" rel="stylesheet" />
</head>
<body class="">
    <div class="page">
      <div class="page-main">
        {% include 'pub/top.html' %}
        <div class="my-3 my-md-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4"></div>
                    <div class="col-lg-4 col-md-12">
                        <div class="card card-profile">
                            <form id="main-form" method="POST" enctype="multipart/form-data">
                                <div class="card-img-top text-center p-5">
                                    <div class="preview">
                                        <span class="avatar avatar-xxl" style="background-image: url({% if user.userheadphoto_set.last.head_portrait %}/media/{{ user.userheadphoto_set.last.head_portrait }}{% else %}/static/image/logo-m.png{% endif %})"></span>
                                    </div>
                                    <div class="custom-file" style="margin-top: 5px;">
                                        <input class="custom-file-input" type="file" name="head_photo" onchange="editHeadPhoto(this);" accept="image/jpeg">
                                        <label class="custom-file-label">选择图片</label>
                                    </div>
                                </div>
                                <div class="card-body text-center">
                                    <div class="form-group">
                                        <label class="form-label">姓名</label>
                                        <input class="form-control text-center" name="name" type="text" value="{{ user.first_name }}">
                                    </div>
                                    {% csrf_token %}
                                    <div id="myInfoEdit" class="btn btn-outline-info">保存</div>
                                    <a href="{% url 'common:myInfo' %}"><div class="btn btn-outline-info">取消</div></a>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-4"></div>
                </div>
            </div>
        </div>
      </div>
      {% include 'pub/footer.html' %}
    </div>
<script src="{% static '/assets/js/require.js' %}"></script>
<script>
      requirejs.config({
          baseUrl: '/static'
      });
      //document.getElementById('home').classList.add('active');
</script>
<script src="{% static '/assets/js/dashboard.js' %}"></script>
<script src="{% static '/assets/plugins/charts-c3/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/maps-google/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/input-mask/plugin.js' %}"></script>
<script>
    function editHeadPhoto(file){
        var prevDiv = $(file).parent().parent().find('.preview');
        if(file.files.length == 0) {
            prevDiv.html('<span class="avatar avatar-xxl" style="background-image: url(/media/{{ user.userheadphoto_set.last.head_portrait }})"></span>');
        }else if (file.files && file.files[0]) {
            var reader = new FileReader();
            reader.onload = function(evt) {
                prevDiv.html('<span class="avatar avatar-xxl" style="background-image: url(' + evt.target.result + ')"></span>')
            }
            reader.readAsDataURL(file.files[0]);
        } else {//IE
            prevDiv.html('<span class="avatar avatar-xxl" style="background-image: url(' + file.value + ')"></span>')
        }
    }
    requirejs(['jquery'], function($){
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $(document).on('click', '#myInfoEdit', function(){
            var form = new FormData(document.getElementById('main-form'));
            $.ajax({
                url: '{% url "common:editMyInfo" %}',
                type: 'POST',
                beforeSend:function(jqXHR, settings){
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        jqXHR.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                },
                data: form,
                processData:false,
                contentType:false,
                success: function(data){
                    if(data.code == 115){
                        window.location.href = '{% url "common:myInfo" %}';
                    }else if(data.code == 116){
                        alert('修改失败, 请刷新页面, 如多次出现请联系管理员. ');
                    }
                }
            });
        });
    });
</script>
  </body>
</html>

templates/user/edit-my-password.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>修改密码 - Remember</title>
    <link rel="icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/dashboard.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/charts-c3/plugin.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/maps-google/plugin.css' %}" rel="stylesheet" />
</head>
<body class="">
    <div class="page">
      <div class="page-main">
        {% include 'pub/top.html' %}
        <div class="my-3 my-md-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4"></div>
                    <div class="col-lg-4 col-md-12">
                        <div class="card card-profile">
                            <div class="card-body text-center">
                                <div id="error-message" class="card-alert alert alert-danger mb-0" style="display: none;"></div>
                                <div class="form-group">
                                    <label class="form-label">原密码</label>
                                    <input class="form-control text-center" placeholder="最短8位,最长16位." minlength="8" maxlength="16" id="old_pwd" name="old_pwd" type="password" required>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">新密码</label>
                                    <input class="form-control text-center" placeholder="最短8位,最长16位." minlength="8" maxlength="16" id="new_pwd" name="new_pwd" type="password" required>
                                </div>
                                <div class="form-group">
                                    <label class="form-label">确认新密码</label>
                                    <input class="form-control text-center" placeholder="最短8位,最长16位." minlength="8" maxlength="16" id="re_new_pwd" name="re_new_pwd" type="password" required>
                                </div>
                                {% csrf_token %}
                                <div id="myPWDEdit" class="btn btn-outline-info">修改</div>
                                <a href="javascript:history.back();"><div class="btn btn-outline-info">取消</div></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4"></div>
                </div>
            </div>
        </div>
      </div>
      {% include 'pub/footer.html' %}
    </div>
<script src="{% static '/assets/js/require.js' %}"></script>
<script>
      requirejs.config({
          baseUrl: '/static'
      });
      //document.getElementById('home').classList.add('active');
</script>
<script src="{% static '/assets/js/dashboard.js' %}"></script>
<script src="{% static '/assets/plugins/charts-c3/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/maps-google/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/input-mask/plugin.js' %}"></script>
<script>
    requirejs(['jquery'], function($){
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $(document).on('click', '#myPWDEdit', function(){
            var old_pwd = $('#old_pwd').val();
            var new_pwd = $('#new_pwd').val();
            var re_new_pwd = $('#re_new_pwd').val();
            if(old_pwd == ''){
                $('#error-message').show();
                $('#error-message').html('请输入原密码.');
                return;
            }
            if(old_pwd.length < 8 || old_pwd.length > 16){
                $('#error-message').show();
                $('#error-message').html('原密码应大于8位小于16位.');
                return;
            }
            if(new_pwd == ''){
                $('#error-message').show();
                $('#error-message').html('请输入新密码.');
                return;
            }
            if(new_pwd.length < 8 || new_pwd.length > 16){
                $('#error-message').show();
                $('#error-message').html('请输入新密码应大于8位小于16位新密码.');
                return;
            }
            if(re_new_pwd == ''){
                $('#error-message').show();
                $('#error-message').html('请输入确认新密码.');
                return;
            }
            if(re_new_pwd.length < 8 || re_new_pwd.length > 16){
                $('#error-message').show();
                $('#error-message').html('确认新密码应大于8位小于16位.');
                return;
            }
            if(new_pwd != re_new_pwd){
                $('#error-message').show();
                $('#error-message').html('两次密码不一致, 请重新输入.');
                return;
            }
            $.ajax({
                url: '{% url "common:editMyPWD" %}',
                type: 'POST',
                beforeSend:function(jqXHR, settings){
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        jqXHR.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                },
                data: {
                    'old_pwd': old_pwd,
                    'new_pwd': new_pwd,
                    're_new_pwd': re_new_pwd
                },
                success: function(data){
                    if(data.code == 117){
                        if(data.old_pwd != undefined) {
                            alert(data.old_pwd[0].message);
                        }
                        if(data.new_pwd != undefined){
                            alert(data.new_pwd[0].message);
                        }
                        if(data.re_new_pwd != undefined){
                            alert(data.re_new_pwd[0].message);
                        }
                    }else if(data.code == 118){
                        $('#error-message').show();
                        $('#error-message').html('您输入原密码不正确, 请重新输入.');
                    }else if(data.code == 119){
                        alert('修改成功\n您的新密码为:' + new_pwd);
                        window.location.href = "{% url 'common:index' %}"
                    }else{
                        $('#error-message').show();
                        $('#error-message').html('可能出现错误, 请联系管理员.');
                        alert('可能出现错误, 请联系管理员.');
                        window.location.href = '{% url "common:editMyPWD" %}'
                    }
                }
            });
        });
    });
</script>
  </body>
</html>

templates/user/my-info.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>个人资料 - Remember</title>
    <link rel="icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static '/image/favicon.ico' %}" type="image/x-icon">
    <link href="{% static '/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static '/assets/css/dashboard.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/charts-c3/plugin.css' %}" rel="stylesheet" />
    <link href="{% static '/assets/plugins/maps-google/plugin.css' %}" rel="stylesheet" />
</head>
<body class="">
    <div class="page">
      <div class="page-main">
        {% include 'pub/top.html' %}
        <div class="my-3 my-md-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4"></div>
                    <div class="col-lg-4 col-md-12">
                        <div class="card card-profile">
                            <div class="card-img-top text-center p-5">
                                <span class="avatar avatar-xxl" style="background-image: url({% if user.userheadphoto_set.last.head_portrait %}/media/{{ user.userheadphoto_set.last.head_portrait }}{% else %}/static/image/logo-m.png{% endif %})"></span>
                            </div>
                            <div class="card-body text-center">
                                <h3 class="mb-3">{{ user.first_name }}</h3>
                                <p class="mb-4">{{ user.username }}</p>
                                <a href="{% url 'common:editMyInfo' %}"><button class="btn btn-outline-info">编辑资料</button></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4"></div>
                </div>
            </div>
        </div>
      </div>
      {% include 'pub/footer.html' %}
    </div>
<script src="{% static '/assets/js/require.js' %}"></script>
<script>
      requirejs.config({
          baseUrl: '/static'
      });
      //document.getElementById('home').classList.add('active');
</script>
<script src="{% static '/assets/js/dashboard.js' %}"></script>
<script src="{% static '/assets/plugins/charts-c3/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/maps-google/plugin.js' %}"></script>
<script src="{% static '/assets/plugins/input-mask/plugin.js' %}"></script>
  </body>
</html>